/*
Existen 2 tipos de datos en JS. Los PRIMITIVOS y los NO PRIMITIVOS.

Los datos PRIMITIVOS son:
Numbers - Integers, floats
Strings - Any data under single quote, double quote or backtick quote
Booleans - true or false value
Null - empty value or no value
Undefined - a declared variable without a value
Symbol - A unique value that can be generated by Symbol constructor

Los datos NO PRIMITIVOS son:
Objects
Arrays

La diferencia entre ellos es que los datos PRIMITIVOS no son modificables una vez creados.
Mientras que los datos NO PRIMITIVOS si son modificables
*/


//DATOS PRIMITIVOS 
let word = 'Hola';
word[0] ='Y'
console.log(word);
// Ejemplo de comparacion de valores entre datos PRIMITIVOS los cuales se comparan directamente con su valor
let numOne = 3;
let numTwo = 3;

console.log(numOne == numTwo);      // true

let js = 'JavaScript';
let py = 'Python';

console.log(js == py);             //false 

let lightOn = true;
let lightOff = false;

console.log(lightOn == lightOff); // false


//DATOS NO PRIMITIVOS
let nums = [0, 1, 2, 3];
nums[0] = 10;

console.log(nums);  // [10, 2, 3]

/* Ejemplo de comparacion entre datos NO PRIMITIVOS que no pueden ser comparados por su valor
Incluso aunque tengan los mismos valores no son exactamente iguales */
let numbers = [0, 1, 2, 3];

console.log(nums == numbers);  // false

let userOne = {
name:'Leonel',
role:'Electronica',
country:'Argentina'
};

let userTwo = {
name:'Leonel',
role:'Electronica',
country:'Argentina'
};

console.log(userOne == userTwo); // false

// Los tipos de datos no prmitivos son extrictamente iguales cuando caen en la misma definicion de variable
let exactNumbers = nums;

console.log(nums == exactNumbers);  // true

let userThree = userOne

console.log(userOne == userThree)  // true